import type { Metadata } from "next";
import { Lato} from "next/font/google";
import "./globals.css";



const LatoFont = Lato({
  variable:"--font-lato",
  weight:["100","400","700"],
  subsets:["latin"]
}) 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${LatoFont.className} antialiased bg-[#181a1b]`}
      >
        {children}
      </body>
    </html>
  );
}
